import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./component/Navbar";
import Discountsofa from "./component/Discountsofa";
import Uniquesofa from "./component/Uniquesofa";
import Shopex from "./component/shopex";
import Product from "./component/Product";
import Hero from "./component/Hero";
import Shop from "./component/Shop";
import Fashon from "./component/Fashon";
import Footer from "./component/Footer";
import Form from "./component/Form";
import Information from "./component/Information";
import Slist from "./component/ShopList/Slist"
import ProductList from "./component/ListProduct/ProductList";
import ProductTable from "./component/ProductTable";
import Login from "./component/login";
import Feature from "./component/AboutFeature/Feature";
import Contact from "./component/ContactUs/Contact";
import FoundError from "./component/Found 404/FoundError";
import FaqInn from "./component/FAQ/FaqInn";
import Headers from "./component/Header";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-[100dvh] flex-col`}
      >
        <div>
        
          
          
        <Headers/>
        <Navbar/>
        <Hero/>
        <Information/>
        <Product/>
        <Discountsofa/>
        <ProductTable/>
        <Fashon/>
        <Shop/>
        <Shopex/>
        <Uniquesofa/>
        <Form/>

        <Slist/>
        <ProductList/>
        <FoundError/>
        <FaqInn/>
        <Feature/>

          
          
         
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}

